# Generated by Django 5.0.6 on 2024-06-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_check_in_photo_attendance_check_out_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='office_end',
            field=models.TimeField(default='17:30:00'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='office_start',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
