# Generated by Django 5.0.6 on 2024-06-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_office_end_attendance_office_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='full_day_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='half_day_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='late_punches',
            field=models.IntegerField(default=0),
        ),
    ]
